### PR TITLE
Added support for node.js and node-amd.

### PR DESCRIPTION
**Pull request by Munawwar**
This will allow unit testing client-side AMD + KO/Lithium UI code on node.js.

### CODE REVIEW

**Comment by papandreou** [comment]
Hi @Munawwar, nice hearing from you, I hope everything is well!

This looks fine and it doesn't break the app I just tested it with, so I'll merge.

**Comment by papandreou** [comment]
Released in 0.4.0.

**Comment by papandreou** [comment]
Ah, damn, only after releasing 0.4.0 I realize that it breaks two tests:

```
  1) tpl should invoke TRHTML on the template if available:

      Error: expected 'Pure text' to be loaded as a template '<html><head></head><body><script type="text/html" id="theTemplateName">Ren tekst</script></body></html>'
      + expected - actual

       {
      -  "$Jsdom": "<html><head></head><body><script type=\"text/html\" id=\"theTemplateName\">Pure text</script></body></html>"
      +  "$Jsdom": "<html><head></head><body><script type=\"text/html\" id=\"theTemplateName\">Ren tekst</script></body></html>"
       }
      
      at Context.<anonymous> (test/tpl.js:71:9)

  2) tpl should invoke TRHTML on the template if available and DEFAULTLOCALEID !== LOCALEID:

      Error: expected 'Pure text' to be loaded as a template '<html><head></head><body><script type="text/html" id="theTemplateName">Ren tekst</script></body></html>'
      + expected - actual

       {
      -  "$Jsdom": "<html><head></head><body><script type=\"text/html\" id=\"theTemplateName\">Pure text</script></body></html>"
      +  "$Jsdom": "<html><head></head><body><script type=\"text/html\" id=\"theTemplateName\">Ren tekst</script></body></html>"
       }
      
      at Context.<anonymous> (test/tpl.js:82:9)
```

Could you take a look?

For some reason I never got around to add Travis etc. to this project.

**Comment by Munawwar** [comment]
Sure, will take a look.

**Comment by Munawwar** [comment]
For me all tests fail. How do you run this? `node_modules/mocha/bin/mocha --reporter spec test/mocha.opts`?

**Comment by Munawwar** [comment]
I think it's time one.com create a chat at gitter.im :) (There is assetgraph one, but that seems like misusing a project specific room.)

**Comment by papandreou** [comment]
Just `mocha` or `npm test`.

The assetgraph channel will be OK, we won't disturb a lot of people there :). I'm going on christmas holiday soon, but maybe we can get a chance to chat tomorrow before lunch, DK time?

**Comment by Munawwar** [comment]
I see the test failing now on node 0.10 (I was using 0.12). Anyway, be there in case I need your input :smile:

**Comment by papandreou** [comment]
Fixed on master, released 0.4.1.

Upgraded the test tooling a bit and added Travis integration. The test suite passes in 0.10, 0.12, 4, and 5: https://travis-ci.org/One-com/requirejs-tpl

**Pull request merged**
